eco_dict = {
	'ecosystem' : 5,
	'platform' : 3,
	'technology' : 2,
	'customer' : 2,
	'development' : 2,
	'community' : 4,
	'complement' : 2,
	'complementor' : 2,
	'collaboration' : 3,
	'marketplace' : 1,
	'customer' : 1,
	'client' : 1,
	'supplier' : 1,
	'buyer' : 1,
	'developer' : 2,
	'synergy' : 4,
	'contract' : 1,
	'alliance' : 3,
	'alliances' : 3,
	'joint ventures' : 3,
	'joint agreement' : 3,
	'eco-system' : 5,
	'complementarities' : 2,
	'stimulate demand' : 2,
	'to leverage existing techologies and projects' : 2,
	'market development' : 2
}

financial_dict = {
	'financial' : 5,
	'equity' : 4,
	'asset' : 4,
	'private equity' : 4,
	'funding' : 4,
	'return' : 3,
	'returns' : 3,
	'financial return' : 5,
	'financial returns' : 5,
	'make money' : 4
}

learning_dict = {
	'novel technologies' : 4,
	'learning' : 5,
	'external environment' : 3,
	'technological continuities' : 3,
	'recognize potential technological opportunities' : 4,
	'to acquire potentially disruptive technologies' : 4,
	'to fill gaps in their technology product' : 4,
	'disrupt' : 4,
	'explore' : 5,
	'exploration' : 5,
	'identify' : 3,
	'recognize' : 3,
	'long-term' : 2,
	'strategic' : 2,
	'learn' : 5,
	'cutting-edge' : 3,
	'patents' : 3,
	'intellectual property' : 4,
	'acquire' : 4,
	'acquisition' : 4,
	'technological' : 3,
	'alliance' : 2
}